### ISSUE TITLE
Regarding the format of ActivityNet

### ISSUE THREAD

**Issue by szbcasia** [IVGSZ/Flash-VStream#19]
Hello, I noticed that in the original dataset of ActivityNet, most files are in MP4 format, while a small percentage are in MKV format, and a very small percentage are in WebM format. However, all the videos in the JSON file you provided are in MP4 format. So, do I need to first convert all the files to MP4 format?
Additionally, is there any other preprocessing required for ActivityNet? When I train using the official dataset downloaded from ActivityNet, the training gets stuck at certain videos. Do you have any solutions or can you provide the training set you used for ActivityNet?

**Comment by zhang9302002** [comment]
Hello, we converted all video files to mp4 format using 
[extract_video_feature_1fps.py.zip](https://github.com/user-attachments/files/17514346/extract_video_feature_1fps.py.zip).
You can try 'scan', 'convert', 'extract' phases to process.

We just download ActivityNet videos from https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/docs/train_video_chatgpt.md . After obtaining the videos, we extract the frames or ViT features of them. Both training from frames and from features is feasible. Training from features is faster on our machine. However, if trained from videos, it can get stuck because IO problems.
