### ISSUE TITLE
What is the filed 'video_id' in the dataset real_time_ego_4d?

### ISSUE THREAD

**Issue by oximi123** [IVGSZ/Flash-VStream#21]
Hi, what is the meaning of 'video_id' in the dataset? I thought it might specify a unique clip of a unique video, but in these two figures with the same video ID, it turns out to be two different video clips.
![image](https://github.com/user-attachments/assets/f4ff2b7a-17cb-4a55-aab1-4b0120469415)
![image](https://github.com/user-attachments/assets/d67fca61-b4e0-43e0-813b-8418c890f617)

**Comment by zhang9302002** [comment]
Hello, thank you.

`video_id` is the id of video file of RVS-ego/movie. Each `video_id` specifies a different video of VStream-QA.

`video_name` is the source video of VStream-QA, which tells where the video comes from. Some videos of VStream-QA can have the same `video_name`.

`start_time`, `end_time`, `gt_duration` tell the ground truth video clip in a video. The answer of one question can be inferred solely from this `gt_duration`. Different questions of the same video can have different `start_time`, `end_time`, `gt_duration` tables, and model should be unaware of this labels during evaluation.

`duration` tells the overall numbers of frames of the video of VStream-QA. Note that for Ego4d fps=1, and for MovieNet fps<1 because we adopt the keyframes from MovieNet.

Therefore, in your two examples, this 2 questions are based on the same video but questioning different parts.

**Comment by oximi123** [comment]
> Hello, thank you.
> 
> `video_id` is the id of video file of RVS-ego/movie. Each `video_id` specifies a different video of VStream-QA.
> 
> `video_name` is the source video of VStream-QA, which tells where the video comes from. Some videos of VStream-QA can have the same `video_name`.
> 
> `start_time`, `end_time`, `gt_duration` tell the ground truth video clip in a video. The answer of one question can be inferred solely from this `gt_duration`. Different questions of the same video can have different `start_time`, `end_time`, `gt_duration` tables, and model should be unaware of this labels during evaluation.
> 
> `duration` tells the overall numbers of frames of the video of VStream-QA. Note that for Ego4d fps=1, and for MovieNet fps<1 because we adopt the keyframes from MovieNet.
> 
> Therefore, in your two examples, this 2 questions are based on the same video but questioning different parts.

So when I cut the original video of Ego-4d for evaluation, I need to cut it based on the `start_time `and `end_time `rather than `video_id`, right?

**Comment by zhang9302002** [comment]
> > Hello, thank you.
> > `video_id` is the id of video file of RVS-ego/movie. Each `video_id` specifies a different video of VStream-QA.
> > `video_name` is the source video of VStream-QA, which tells where the video comes from. Some videos of VStream-QA can have the same `video_name`.
> > `start_time`, `end_time`, `gt_duration` tell the ground truth video clip in a video. The answer of one question can be inferred solely from this `gt_duration`. Different questions of the same video can have different `start_time`, `end_time`, `gt_duration` tables, and model should be unaware of this labels during evaluation.
> > `duration` tells the overall numbers of frames of the video of VStream-QA. Note that for Ego4d fps=1, and for MovieNet fps<1 because we adopt the keyframes from MovieNet.
> > Therefore, in your two examples, this 2 questions are based on the same video but questioning different parts.
> 
> So when I cut the original video of Ego-4d for evaluation, I need to cut it based on the `start_time `and `end_time `rather than `video_id`, right?

Nope, you need to cut video according to vstream/vs_ego.json or vstream-realtime/rvs_ego.json, following the instruction of https://huggingface.co/datasets/IVGSZ/VStream-QA
