### ISSUE TITLE
How to Download the Video of VStream-QA Benchmark

### ISSUE THREAD

**Issue by JUNJIE99** [IVGSZ/Flash-VStream#4]
Hi,

Thank you for your great work.

I would like to ask if the VStream-QA benchmark video is available for download? I only found json files at this [link](https://huggingface.co/datasets/IVGSZ/VStream-QA).

Looking forward to your reply, thank you!

**Comment by zhang9302002** [comment]
Hi, thanks for your attention!

The videos of VStream-QA benchmark are clipped from videos of Ego4D and MovieNet. Due to copyright reasons, we can only provide the annotation json files. To get the videos, you need to follow the instructions from the official website of Ego4D and MovieNet.

You can refer to this [instruction](https://huggingface.co/datasets/IVGSZ/VStream-QA#preparation) to prepare the benchmark videos and corresponding annotations.

Thank you for your understanding!

**Comment by JUNJIE99** [comment]
Thanks for your reply.
